In [21]:
import pandas as pd
from sklearn.metrics import mean_absolute_error

In [2]:
orders_df = pd.read_csv("orders.csv")
items_df = pd.read_csv("order_items.csv")
product_variants_df = pd.read_csv("product_variants.csv")
products_df = pd.read_csv("products.csv")

In [7]:
product = products_df[
    products_df["name"] == "Bússola de Bordo 702"
]

product.info()
print("\n")
product.head()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 73 to 239
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2 non-null      int64
 1   name             2 non-null      object
 2   description      2 non-null      object
 3   brand_id         2 non-null      int64
 4   category_id      2 non-null      int64
 5   ncm_code         2 non-null      int64
 6   unit_of_measure  2 non-null      object
 7   is_active        2 non-null      bool
 8   created_at       2 non-null      object
 9   updated_at       2 non-null      object
dtypes: bool(1), int64(4), object(5)
memory usage: 162.0+ bytes

,id,name,description,brand_id,category_id,ncm_code,unit_of_measure,is_active,created_at,updated_at
73,74,Bússola de Bordo 702,Bússola magnética líquida com iluminação,12,8,18607512,UN,True,2025-01-27 17:41:23,2025-04-09 17:31:25
239,240,Bússola de Bordo 702,Bússola magnética líquida com iluminação,8,7,91287147,UN,True,2026-06-22 00:02:10,2026-11-18 21:03:07

In [ ]:
# a versao com id 240 nao deve entrar na analise por que ele nao
  # existia no sistema da loja durante o periodo a ser analisado

In [17]:
product_id = 74

product_variants = product_variants_df[
    product_variants_df["product_id"] == product_id
]

product_variant_ids = product_variants["id"]

product_variants.info()
print("\n")
product_variants.head()
print("\n")
print("Variantes do produto:")
print(product_variants)
print()
print("\n")
product_variants.head()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 146 to 147
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           2 non-null      int64
 1   product_id   2 non-null      int64
 2   sku          2 non-null      object
 3   barcode_ean  2 non-null      float64
 4   sale_price   2 non-null      float64
 5   cost_price   2 non-null      float64
 6   weight_kg    2 non-null      float64
 7   icms_rate    2 non-null      float64
 8   ipi_rate     2 non-null      float64
 9   is_active    2 non-null      bool
 10  created_at   2 non-null      object
 11  updated_at   2 non-null      object
dtypes: bool(1), float64(6), int64(2), object(3)
memory usage: 194.0+ bytes




Variantes do produto:
      id  product_id         sku   barcode_ean  sale_price  cost_price  \
146  147          74  LHN-677223  8.001228e+12     3400.77     1899.87
147  148          74  LHN-795790  3.257483e+12     1235.13      620.67

     weight_kg  icms_rate  ipi_rate  is_active           created_at  \
146     41.792       17.0       5.0       True  2026-12-18 10:09:50
147     39.943       17.0      10.0       True  2024-05-29 07:55:29

              updated_at
146  2026-12-20 14:34:20
147  2024-06-21 10:25:16

,id,product_id,sku,barcode_ean,sale_price,cost_price,weight_kg,icms_rate,ipi_rate,is_active,created_at,updated_at
146,147,74,LHN-677223,8.001228e+12,3400.77,1899.87,41.792,17.0,5.0,True,2026-12-18 10:09:50,2026-12-20 14:34:20
147,148,74,LHN-795790,3.257483e+12,1235.13,620.67,39.943,17.0,10.0,True,2024-05-29 07:55:29,2024-06-21 10:25:16

In [ ]:
# a variante com id 147 (sku LHN-677223) tem data de criacao alem do periodo analisado
  # entao nao entra no estudo

In [19]:
product_variants_2 = product_variants_df[
    (product_variants_df["product_id"] == product_id) &
    (pd.to_datetime(product_variants_df["created_at"]) <= "2025-12-31")
]

product_variants_2.info()
print("\n")
product_variants_2.head()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 147 to 147
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           1 non-null      int64
 1   product_id   1 non-null      int64
 2   sku          1 non-null      object
 3   barcode_ean  1 non-null      float64
 4   sale_price   1 non-null      float64
 5   cost_price   1 non-null      float64
 6   weight_kg    1 non-null      float64
 7   icms_rate    1 non-null      float64
 8   ipi_rate     1 non-null      float64
 9   is_active    1 non-null      bool
 10  created_at   1 non-null      object
 11  updated_at   1 non-null      object
dtypes: bool(1), float64(6), int64(2), object(3)
memory usage: 97.0+ bytes

,id,product_id,sku,barcode_ean,sale_price,cost_price,weight_kg,icms_rate,ipi_rate,is_active,created_at,updated_at
147,148,74,LHN-795790,3.257483e+12,1235.13,620.67,39.943,17.0,10.0,True,2024-05-29 07:55:29,2024-06-21 10:25:16

In [20]:
print("Variantes consideradas:")
print(product_variants)
print()

Variantes consideradas:
      id  product_id         sku   barcode_ean  sale_price  cost_price  \
147  148          74  LHN-795790  3.257483e+12     1235.13      620.67

     weight_kg  icms_rate  ipi_rate  is_active           created_at  \
147     39.943       17.0      10.0       True  2024-05-29 07:55:29

              updated_at
147  2024-06-21 10:25:16

In [29]:
product_items = items_df[
    items_df["product_variant_id"].isin(
        product_variants_2["id"]
    )
].copy()
# product_items agora contem as ocorrencias de item em pedido que sao o produto estudado

print("Itens vendidos da variante:")
print(product_items.info())
print("\n")
print(product_items.head())
print("\n")
print(f"Quantidade de registros: {len(product_items)}")
print()
print("\n")
print(f"Unidades vendidas do produto 148: {product_items["quantity"].sum()}")

Itens vendidos da variante:
<class 'pandas.core.frame.DataFrame'>
Index: 171 entries, 452 to 146497
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  171 non-null    int64
 1   order_id            171 non-null    int64
 2   product_variant_id  171 non-null    int64
 3   quantity            171 non-null    int64
 4   unit_price          171 non-null    float64
 5   icms_rate           171 non-null    float64
 6   ipi_rate            171 non-null    float64
 7   line_total          171 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 12.0 KB
None


        id  order_id  product_variant_id  quantity  unit_price  icms_rate  \
452    457       150                 148         2     1235.13       17.0
1208  1222       397                 148         7     1235.13       17.0
1716  1737       563                 148         1     1235.13       17.0
1756  1777       576                 148         2     1235.13       17.0
1823  1844       599                 148         2     1235.13       17.0

      ipi_rate  line_total
452       10.0     2470.26
1208      10.0     8645.91
1716      10.0     1235.13
1756      10.0     2470.26
1823      10.0     2470.26


Quantidade de registros: 171



Unidades vendidas do produto 148: 878

In [ ]:
# o produto com id de variante 148 apareceu em 171 pedidos e teve 878 unidades vendidas

In [28]:
print(
    f"Quantidade de pedidos: {product_items['order_id'].nunique()}"
)

Quantidade de pedidos: 171

In [31]:
# pegando da tabela orders os pedidos com id em product_items
  # que possui os registros de venda do produto especifico
dataset = product_items.merge(
    orders_df[["id", "placed_at"]],
    left_on="order_id",
    right_on="id",
    how="inner"
)

print("Dataset unificado:")
print(dataset.info())
print("\n")
print(dataset.head())
print("\n")
print(f"Quantidade de registros: {len(dataset)}")
print()

Dataset unificado:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_x                171 non-null    int64
 1   order_id            171 non-null    int64
 2   product_variant_id  171 non-null    int64
 3   quantity            171 non-null    int64
 4   unit_price          171 non-null    float64
 5   icms_rate           171 non-null    float64
 6   ipi_rate            171 non-null    float64
 7   line_total          171 non-null    float64
 8   id_y                171 non-null    int64
 9   placed_at           171 non-null    object
dtypes: float64(4), int64(5), object(1)
memory usage: 13.5+ KB
None


   id_x  order_id  product_variant_id  quantity  unit_price  icms_rate  \
0   457       150                 148         2     1235.13       17.0
1  1222       397                 148         7     1235.13       17.0
2  1737       563                 148         1     1235.13       17.0
3  1777       576                 148         2     1235.13       17.0
4  1844       599                 148         2     1235.13       17.0

   ipi_rate  line_total  id_y            placed_at
0      10.0     2470.26   150  2025-01-13 05:12:49
1      10.0     8645.91   397  2020-02-13 02:02:06
2      10.0     1235.13   563  2024-03-22 15:47:59
3      10.0     2470.26   576  2024-02-04 04:28:47
4      10.0     2470.26   599  2021-03-05 14:23:56


Quantidade de registros: 171

In [34]:
# transformando a coluna em data
dataset["placed_at"] = pd.to_datetime(
    dataset["placed_at"]
)


# criando coluna de mes no dataset
dataset["month"] = dataset["placed_at"].dt.to_period("M")

print("Dataset com mês:")
dataset.info()
print("\n")
print(
    dataset[
        ["order_id", "quantity", "placed_at", "month"]
    ].head()
)
print()

Dataset com mês:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_x                171 non-null    int64
 1   order_id            171 non-null    int64
 2   product_variant_id  171 non-null    int64
 3   quantity            171 non-null    int64
 4   unit_price          171 non-null    float64
 5   icms_rate           171 non-null    float64
 6   ipi_rate            171 non-null    float64
 7   line_total          171 non-null    float64
 8   id_y                171 non-null    int64
 9   placed_at           171 non-null    datetime64[ns]
 10  month               171 non-null    period[M]
dtypes: datetime64[ns](1), float64(4), int64(5), period[M](1)
memory usage: 14.8 KB


   order_id  quantity           placed_at    month
0       150         2 2025-01-13 05:12:49  2025-01
1       397         7 2020-02-13 02:02:06  2020-02
2       563         1 2024-03-22 15:47:59  2024-03
3       576         2 2024-02-04 04:28:47  2024-02
4       599         2 2021-03-05 14:23:56  2021-03

In [35]:
# agrupando as vendas do produto por mes
monthly_sales = (
    dataset
    .groupby("month", as_index=False)["quantity"]
    .sum()
    .rename(
        columns={"quantity": "units_sold"}
    )
)

print("Vendas mensais:")
print(monthly_sales)
print()

Vendas mensais:
      month  units_sold
0   2020-01           9
1   2020-02          14
2   2020-03           1
3   2020-04          13
4   2020-07           4
..      ...         ...
59  2026-08          21
60  2026-09          33
61  2026-10          11
62  2026-11          27
63  2026-12          33

[64 rows x 2 columns]

In [ ]:
# alguns meses nao aparecem, por que teve 0 vendas do produto nele
  # exemplo: 2020-05, 2020-06
  # necessario marcar com 0 para nao inflar a contagem

In [36]:
# adicionando meses que nao aparecem (pois tiveram 0 vendas do produto)
all_months = pd.period_range(
    start=monthly_sales["month"].min(),
    end="2026-03",
    freq="M"
)

monthly_sales = (
    monthly_sales
    .set_index("month")
    .reindex(all_months, fill_value=0)
    .rename_axis("month")
    .reset_index()
)

print("Série mensal completa:")
print(monthly_sales)
print()

Série mensal completa:
      month  units_sold
0   2020-01           9
1   2020-02          14
2   2020-03           1
3   2020-04          13
4   2020-05           0
..      ...         ...
70  2025-11          16
71  2025-12           0
72  2026-01          26
73  2026-02          24
74  2026-03          10

[75 rows x 2 columns]

In [40]:
# separando dados de treino e teste
train = monthly_sales[
    monthly_sales["month"] <= pd.Period("2025-12")
].copy()

test = monthly_sales[
    monthly_sales["month"].between(
        pd.Period("2026-01"),
        pd.Period("2026-03")
    )
].copy()

print("Dados de treino:")
print(train)
print('\n')
train.info()
print('\n')

print("Dados de teste:")
print(test)
print()
test.info()

Dados de treino:
      month  units_sold
0   2020-01           9
1   2020-02          14
2   2020-03           1
3   2020-04          13
4   2020-05           0
..      ...         ...
67  2025-08           0
68  2025-09          16
69  2025-10          16
70  2025-11          16
71  2025-12           0

[72 rows x 2 columns]


<class 'pandas.core.frame.DataFrame'>
Index: 72 entries, 0 to 71
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   month       72 non-null     period[M]
 1   units_sold  72 non-null     int64
dtypes: int64(1), period[M](1)
memory usage: 1.7 KB


Dados de teste:
      month  units_sold
72  2026-01          26
73  2026-02          24
74  2026-03          10

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 72 to 74
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   month       3 non-null      period[M]
 1   units_sold  3 non-null      int64
dtypes: int64(1), period[M](1)
memory usage: 72.0 bytes

In [47]:
# media movel dos ultimos 3 meses
predictions = []

history = train["units_sold"].tolist()

for _, row in test.iterrows():
    prediction = sum(history[-3:]) / 3
    predictions.append(prediction)
    last_3_months = history[-3:]
    print(
        f"Mês previsto: {row['month']} | "
        f"Últimos 3 meses: {last_3_months} | "
        f"Média: {prediction:.2f} | "
        f"Valor real: {row['units_sold']}"
    )
    history.append(row["units_sold"])

test["prediction"] = predictions


# previsoes pro 1o trimeste de 2026

Mês previsto: 2026-01 | Últimos 3 meses: [16, 16, 0] | Média: 10.67 | Valor real: 26
Mês previsto: 2026-02 | Últimos 3 meses: [16, 0, 26] | Média: 14.00 | Valor real: 24
Mês previsto: 2026-03 | Últimos 3 meses: [0, 26, 24] | Média: 16.67 | Valor real: 10

In [48]:
mae = mean_absolute_error(
    test["units_sold"],
    test["prediction"]
)

print(f"MAE: {mae:.2f} unidades")

MAE: 10.67 unidades

In [55]:
predictions = []

history = train["units_sold"].tolist()

for _, row in test.iterrows():
    prediction2 = sum(history[-6:]) / 6
    predictions.append(prediction2)
    last_6_months = history[-6:]
    print(
        f"Mês previsto: {row['month']} | "
        f"Últimos 6 meses: {last_6_months} | "
        f"Média: {prediction2:.2f} | "
        f"Valor real: {row['units_sold']}"
    )
    history.append(row["units_sold"])

test["prediction2"] = predictions


# previsoes utilizando ultimos 6 meses

Mês previsto: 2026-01 | Últimos 6 meses: [14, 0, 16, 16, 16, 0] | Média: 10.33 | Valor real: 26
Mês previsto: 2026-02 | Últimos 6 meses: [0, 16, 16, 16, 0, 26] | Média: 12.33 | Valor real: 24
Mês previsto: 2026-03 | Últimos 6 meses: [16, 16, 16, 0, 26, 24] | Média: 16.33 | Valor real: 10

In [56]:
mae = mean_absolute_error(
    test["units_sold"],
    test["prediction2"]
)

print(f"MAE: {mae:.2f} unidades ()")

MAE: 11.22 unidades ()

In [57]:
predictions = []

history = train["units_sold"].tolist()

for _, row in test.iterrows():
    prediction3 = sum(history[-12:]) / 12
    predictions.append(prediction3)
    last_12_months = history[-12:]
    print(
        f"Mês previsto: {row['month']} | "
        f"Últimos 12 meses: {last_12_months} | "
        f"Média: {prediction3:.2f} | "
        f"Valor real: {row['units_sold']}"
    )
    history.append(row["units_sold"])

test["prediction3"] = predictions


# previsoes utilizando ultimos 12 meses

print("\n")
mae = mean_absolute_error(
    test["units_sold"],
    test["prediction3"]
)

print(f"MAE: {mae:.2f} unidades ()")

Mês previsto: 2026-01 | Últimos 12 meses: [2, 10, 22, 12, 0, 0, 14, 0, 16, 16, 16, 0] | Média: 9.00 | Valor real: 26
Mês previsto: 2026-02 | Últimos 12 meses: [10, 22, 12, 0, 0, 14, 0, 16, 16, 16, 0, 26] | Média: 11.00 | Valor real: 24
Mês previsto: 2026-03 | Últimos 12 meses: [22, 12, 0, 0, 14, 0, 16, 16, 16, 0, 26, 24] | Média: 12.17 | Valor real: 10


MAE: 10.72 unidades ()

In [60]:
# testando com o mesmo periodo, do ano anterior
sales_2025 = monthly_sales[
    monthly_sales["month"].dt.year == 2025
].copy()

test = monthly_sales[
    monthly_sales["month"].between(
        pd.Period("2026-01"),
        pd.Period("2026-03")
    )
].copy()

predictions4 = []

for _, row in test.iterrows():

    previous_year_month = row["month"] - 12

    previous_year_sales = monthly_sales[
        monthly_sales["month"] == previous_year_month
    ]["units_sold"]

    prediction = previous_year_sales.iloc[0]

    predictions4.append(prediction)

    print(
        f"Mês previsto: {row['month']} | "
        f"Mesmo mês de 2025: {previous_year_month} | "
        f"Previsão: {prediction} | "
        f"Valor real: {row['units_sold']}"
    )

test["prediction4"] = predictions4

print("\n")
mae = mean_absolute_error(
    test["units_sold"],
    test["prediction4"]
)

print(f"MAE: {mae:.2f} unidades")

Mês previsto: 2026-01 | Mesmo mês de 2025: 2025-01 | Previsão: 2 | Valor real: 26
Mês previsto: 2026-02 | Mesmo mês de 2025: 2025-02 | Previsão: 10 | Valor real: 24
Mês previsto: 2026-03 | Mesmo mês de 2025: 2025-03 | Previsão: 22 | Valor real: 10


MAE: 16.67 unidades

In [ ]:
"""
O baseline não é adequado, por que não apresentou um bom desempenho para esse produto.

No 1o trimestre de 2026, a média móvel dos últimos 3 meses apresentou um MAE de 10,67
unidades, ou seja, as previsões erraram, em média, cerca de 11 unidades por mês. Até
utilizando outras quantidades de meses passados (6 e 12 meses), o MAE continuou nessa faixa.

Considerando que as vendas reais foram de 26, 24 e 10 unidades nos meses avaliados,
o erro é relativamente alto em relação ao volume vendido.
"""

In [62]:
"""
Uma limitação desse método de avaliação de demanda futura é que ele não leva em conta questões
que vão além dos dados presentes nas colunas. De um ano para outro a economia muda e a chance das
pessoas comprarem um certo produto muda junto com isso.
Além disso, usar os 3 últimos meses também não leva em consideração o período do ano, dado que
certos itens tendem a ser comprados mais em certas épocas ou estações.
"""

'\nUma limitação desse método de avaliação de demanda futura é que ele não leva em conta questões que vão além dos dados presentes nas \n'